// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import * as WOS from "./wos";
import type { WaveEnv } from "@/app/waveenv/waveenv";

function callBackendService(waveEnv: WaveEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {
    if (waveEnv != null) {
        return waveEnv.callBackendService(service, method, args, noUIContext)
    }
    return WOS.callBackendService(service, method, args, noUIContext);
}

// blockservice.BlockService (block)
export class BlockServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // queue a layout action to cleanup orphaned blocks in the tab
    // @returns object updates
    CleanupOrphanedBlocks(tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "CleanupOrphanedBlocks", Array.from(arguments))
    }
    GetControllerStatus(arg2: string): Promise<BlockControllerRuntimeStatus> {
        return callBackendService(this?.waveEnv, "block", "GetControllerStatus", Array.from(arguments))
    }

    // move a block to another tab of the same workspace (empty destTabId creates a new tab)
    // @returns MoveBlockRtn (and object updates)
    MoveBlockToTab(blockId: string, destTabId: string): Promise<MoveBlockRtn> {
        return callBackendService(this?.waveEnv, "block", "MoveBlockToTab", Array.from(arguments))
    }

    // move a block to another tab of the same workspace, split next to targetBlockId on side (left/right/top/bottom)
    // @returns MoveBlockRtn (and object updates)
    MoveBlockToTabAt(blockId: string, destTabId: string, targetBlockId: string, side: string): Promise<MoveBlockRtn> {
        return callBackendService(this?.waveEnv, "block", "MoveBlockToTabAt", Array.from(arguments))
    }

    // save the terminal state to a blockfile
    SaveTerminalState(blockId: string, state: string, stateType: string, ptyOffset: number, termSize: TermSize): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "SaveTerminalState", Array.from(arguments))
    }
}

export const BlockService = new BlockServiceType();

// clientservice.ClientService (client)
export class ClientServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns object updates
    AgreeTos(): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "AgreeTos", Array.from(arguments))
    }
    FocusWindow(arg2: string): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "FocusWindow", Array.from(arguments))
    }
    GetAllConnStatus(): Promise<ConnStatus[]> {
        return callBackendService(this?.waveEnv, "client", "GetAllConnStatus", Array.from(arguments))
    }
    GetClientData(): Promise<Client> {
        return callBackendService(this?.waveEnv, "client", "GetClientData", Array.from(arguments))
    }
    GetTab(arg1: string): Promise<Tab> {
        return callBackendService(this?.waveEnv, "client", "GetTab", Array.from(arguments))
    }
    TelemetryUpdate(arg2: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "TelemetryUpdate", Array.from(arguments))
    }
}

export const ClientService = new ClientServiceType();

// objectservice.ObjectService (object)
export class ObjectServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns blockId (and object updates)
    CreateBlock(blockDef: BlockDef, rtOpts: RuntimeOpts): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "CreateBlock", Array.from(arguments))
    }

    // @returns object updates
    DeleteBlock(blockId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "DeleteBlock", Array.from(arguments))
    }

    // get wave object by oref
    GetObject(oref: string): Promise<WaveObj> {
        return callBackendService(this?.waveEnv, "object", "GetObject", Array.from(arguments))
    }

    // @returns objects
    GetObjects(orefs: string[]): Promise<WaveObj[]> {
        return callBackendService(this?.waveEnv, "object", "GetObjects", Array.from(arguments))
    }

    // @returns object updates
    UpdateObject(waveObj: WaveObj, returnUpdates: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObject", Array.from(arguments))
    }

    // @returns object updates
    UpdateObjectMeta(oref: string, meta: MetaType): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObjectMeta", Array.from(arguments))
    }
}

export const ObjectService = new ObjectServiceType();

// userinputservice.UserInputService (userinput)
export class UserInputServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    SendUserInputResponse(arg1: UserInputResponse): Promise<void> {
        return callBackendService(this?.waveEnv, "userinput", "SendUserInputResponse", Array.from(arguments))
    }
}

export const UserInputService = new UserInputServiceType();

// windowservice.WindowService (window)
export class WindowServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    CloseWindow(windowId: string, fromElectron: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "CloseWindow", Array.from(arguments))
    }

    // create a new tab shown in the given window and make it that window's active tab
    // @returns tabId (and object updates)
    CreateTabInWindow(windowId: string): Promise<string> {
        return callBackendService(this?.waveEnv, "window", "CreateTabInWindow", Array.from(arguments))
    }
    CreateWindow(winSize: WinSize, workspaceId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "CreateWindow", Array.from(arguments))
    }
    GetWindow(windowId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "GetWindow", Array.from(arguments))
    }

    // move a tab to another window of the same workspace (index -1 appends)
    // @returns TabWindowMoveRtn (and object updates)
    MoveTabToWindow(tabId: string, destWindowId: string, index: number): Promise<TabWindowMoveRtn> {
        return callBackendService(this?.waveEnv, "window", "MoveTabToWindow", Array.from(arguments))
    }

    // move a block into a new tab in a new popped-out window of the same workspace
    // @returns PopOutRtn (and object updates)
    PopOutBlock(blockId: string, pos: Point, size: WinSize): Promise<PopOutRtn> {
        return callBackendService(this?.waveEnv, "window", "PopOutBlock", Array.from(arguments))
    }

    // move a tab into a new popped-out window of the same workspace
    // @returns PopOutRtn (and object updates)
    PopOutTab(tabId: string, pos: Point, size: WinSize): Promise<PopOutRtn> {
        return callBackendService(this?.waveEnv, "window", "PopOutTab", Array.from(arguments))
    }

    // set window position and size
    // @returns object updates
    SetWindowPosAndSize(windowId: string, pos: Point, size: WinSize): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "SetWindowPosAndSize", Array.from(arguments))
    }
    SwitchWorkspace(windowId: string, workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "window", "SwitchWorkspace", Array.from(arguments))
    }
}

export const WindowService = new WindowServiceType();

// workspaceservice.WorkspaceService (workspace)
export class WorkspaceServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns CloseTabRtn (and object updates)
    CloseTab(workspaceId: string, tabId: string, fromElectron: boolean): Promise<CloseTabRtnType> {
        return callBackendService(this?.waveEnv, "workspace", "CloseTab", Array.from(arguments))
    }

    // @returns tabId (and object updates)
    CreateTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateTab", Array.from(arguments))
    }

    // @returns workspaceId
    CreateWorkspace(name: string, icon: string, color: string, applyDefaults: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateWorkspace", Array.from(arguments))
    }

    // @returns object updates
    DeleteWorkspace(workspaceId: string): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "DeleteWorkspace", Array.from(arguments))
    }

    // @returns colors
    GetColors(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetColors", Array.from(arguments))
    }

    // @returns icons
    GetIcons(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetIcons", Array.from(arguments))
    }

    // @returns workspace
    GetWorkspace(workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "workspace", "GetWorkspace", Array.from(arguments))
    }
    ListWorkspaces(): Promise<WorkspaceListEntry[]> {
        return callBackendService(this?.waveEnv, "workspace", "ListWorkspaces", Array.from(arguments))
    }

    // @returns object updates
    SetActiveTab(workspaceId: string, tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "SetActiveTab", Array.from(arguments))
    }

    // @returns object updates
    UpdateWorkspace(workspaceId: string, name: string, icon: string, color: string, applyDefaults: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "UpdateWorkspace", Array.from(arguments))
    }
}

export const WorkspaceService = new WorkspaceServiceType();

export const AllServiceTypes = {
    "block": BlockServiceType,
    "client": ClientServiceType,
    "object": ObjectServiceType,
    "userinput": UserInputServiceType,
    "window": WindowServiceType,
    "workspace": WorkspaceServiceType,
};

export const AllServiceImpls = {
    "block": BlockService,
    "client": ClientService,
    "object": ObjectService,
    "userinput": UserInputService,
    "window": WindowService,
    "workspace": WorkspaceService,
};
